### ISSUE TITLE
Simulations without seed via nlrx

### ISSUE THREAD

**Issue by Z3tt** [nldoc/nlrx#6]
Hi, is it possible to run simulations without setting any seeds via the nlrx functions? I tried several setups but none of the setups and twists has allowed me to keep the seed I set in the NetLogo code. The reasoning is that I vary the landscape together with the seed (e.g. landscape i with seed i for several setups) and thus would need to specify it on my own.

**Comment by nldoc** [comment]
Hey, basically you have two options when it comes to random seed management. See also the "Comments on seed management" section in the further notes article (https://nldoc.github.io/nlrx/articles/getstarted.html#comments-on-seed-management). 
Option 1: Let nlrx set the random seed. If you want to do this, choose an appropriate number of seeds when defining your simdesign (nseeds). The model seed will then by seed during startup of the model.
Option 2: Set the random seed manually. 
You can just use the NetLogo primitive `random-seed <value>`  to reset the random-seed, for example within your setup procedure. This will overwrite the startup random-seed from nlrx. However, in the output tibble from run_nl_all() you will still see the original nlrx random-seed and not the actual value that has been set during the model run.

Based on this, if I understand your problem correctly, I would do the following:
- I assume you have to inputs on your GUI: `landscape` and `rnd-seed-gui`
- In your setup procedure, manually set the random seed: `random-seed rnd-seed-gui`
- For your nlrx setup, use the distinct simdesign to pair landscapes to random-seeds:
```
variables = list("landscape" = list(values=c("ls1", "ls2", ..., "lsi")),
                        "rnd-seed" = list(values=c(seed1, seed2, seed3, ..., seedi)))
```
- Include the variable `rnd-seed-gui` in the metrics vector to measure your actual random-seed
- Set the nseeds variable of the simdesign to 1, because there is no need to loop over several seeds when you reset the seed manually.

One additional note if you want to combine this approach with other simdesigns. Maybe you want to add additional variables but still want to have matching pairs for your landscapes and seeds. If you would use a full-factorial simdesign for the variables listed above, you would get combinations such as landscape1 - seed3. One option to solve this is to set the `rnd-seed-gui` variable in NetLogo based on the current landscape. For example, in the setup procedure you could check which landscape was chosen for the current run and then set the `rnd-seed-gui` variable accordingly then update the model random-seed. There is no need then to add `rnd-seed-gui` to the variables slot, but if you include `rnd-seed-gui` in the metrics vector, you can still measure your actual random-seed that was used for the current run.
Cheers,
Jan

**Comment by Z3tt** [comment]
Hi Jan, thanks for your comprehensive answer!

Yes, you got it right and this is exactly the way I have set up my model and also the setup procedure. Long story, short solution: I messed up my seed in the NetLogo model and thus thought your random-seed is overwriting mine (which does not make any sense at all assuming the general NL structure and that's why I couldn't explain it to myself).
